routes/web.php
<?php

use App\Http\Controllers\API;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\ReportUserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\UserController;
use Database\Seeders\CreatePermissionSeeder;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.index');
});

Route::get('upgrade-to-v3-4-0', function () {
    try {
        \Artisan::call('migrate', [
            '--path'  => '/database/migrations/2020_10_19_133700_move_all_existing_devices_to_new_table.php',
            '--force' => true,
        ]);

        return 'You are successfully migrated to v3.4.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Route::get('/upgrade-to-v4-3-0', function () {
    try {
        Artisan::call('db:seed', ['--class' => 'CreatePermissionSeeder']);

        return 'You are successfully seeded to v4.3.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Route::get('upgrade-to-v5-0-0', function () {
    try {
        \Artisan::call('migrate', [
            '--path'  => '/database/migrations/2021_07_12_000000_add_uuid_to_failed_jobs_table.php',
            '--force' => true,
        ]);

        return 'You are successfully migrated to v5.0.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Auth::routes();
Route::get('activate', [AuthController::class, 'verifyAccount']);

Route::get('/home', [HomeController::class, 'index']);
Route::post('update-language', [UserController::class, 'updateLanguage'])->middleware('auth');

// Impersonate Logout
Route::get('/users/impersonate-logout', [UserController::class, 'userImpersonateLogout'])->name('impersonate.userLogout');

Route::group(['middleware' => ['user.activated', 'auth']], function () {
    //view routes
    Route::get('/conversations',
        [ChatController::class, 'index'])->name('conversations')->middleware('permission:manage_conversations');
    Route::get('profile', [UserController::class, 'getProfile']);
    Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);

    //get all user list for chat
    Route::get('users-list', [API\UserAPIController::class, 'getUsersList']);
    Route::get('get-users', [API\UserAPIController::class, 'getUsers']);
    Route::delete('remove-profile-image', [API\UserAPIController::class, 'removeProfileImage']);
    /** Change password */
    Route::post('change-password', [API\UserAPIController::class, 'changePassword']);
    Route::get('conversations/{ownerId}/archive-chat', [API\UserAPIController::class, 'archiveChat']);

    Route::get('get-profile', [API\UserAPIController::class, 'getProfile']);
    Route::post('profile', [API\UserAPIController::class, 'updateProfile'])->name('update.profile');
    Route::post('update-last-seen', [API\UserAPIController::class, 'updateLastSeen']);

    Route::post('send-message',
        [API\ChatAPIController::class, 'sendMessage'])->name('conversations.store')->middleware('sendMessage');
    Route::get('users/{id}/conversation', [API\UserAPIController::class, 'getConversation']);
    Route::get('conversations-list', [API\ChatAPIController::class, 'getLatestConversations']);
    Route::get('archive-conversations', [API\ChatAPIController::class, 'getArchiveConversations']);
    Route::post('read-message', [API\ChatAPIController::class, 'updateConversationStatus']);
    Route::post('file-upload', [API\ChatAPIController::class, 'addAttachment'])->name('file-upload');
    Route::post('image-upload', [API\ChatAPIController::class, 'imageUpload'])->name('image-upload');
    Route::get('conversations/{userId}/delete', [API\ChatAPIController::class, 'deleteConversation']);
    Route::post('conversations/message/{conversation}/delete', [API\ChatAPIController::class, 'deleteMessage']);
    Route::post('conversations/{conversation}/delete', [API\ChatAPIController::class, 'deleteMessageForEveryone']);
    Route::get('/conversations/{conversation}', [API\ChatAPIController::class, 'show']);
    Route::post('send-chat-request', [API\ChatAPIController::class, 'sendChatRequest'])->name('send-chat-request');
    Route::post('accept-chat-request',
        [API\ChatAPIController::class, 'acceptChatRequest'])->name('accept-chat-request');
    Route::post('decline-chat-request',
        [API\ChatAPIController::class, 'declineChatRequest'])->name('decline-chat-request');

    /** Web Notifications */
    Route::put('update-web-notifications', [API\UserAPIController::class, 'updateNotification']);

    /** BLock-Unblock User */
    Route::put('users/{user}/block-unblock', [API\BlockUserAPIController::class, 'blockUnblockUser']);
    Route::get('blocked-users', [API\BlockUserAPIController::class, 'blockedUsers']);

    /** My Contacts */
    Route::get('my-contacts', [API\UserAPIController::class, 'myContacts'])->name('my-contacts');

    /** Groups API */
    Route::post('groups', [API\GroupAPIController::class, 'create']);
    Route::post('groups/{group}', [API\GroupAPIController::class, 'update']);
    Route::get('groups', [API\GroupAPIController::class, 'index']);
    Route::get('groups/{group}', [API\GroupAPIController::class, 'show']);
    Route::put('groups/{group}/add-members', [API\GroupAPIController::class, 'addMembers']);
    Route::delete('groups/{group}/members/{user}', [API\GroupAPIController::class, 'removeMemberFromGroup']);
    Route::delete('groups/{group}/leave', [API\GroupAPIController::class, 'leaveGroup']);
    Route::delete('groups/{group}/remove', [API\GroupAPIController::class, 'removeGroup']);
    Route::put('groups/{group}/members/{user}/make-admin', [API\GroupAPIController::class, 'makeAdmin']);
    Route::put('groups/{group}/members/{user}/dismiss-as-admin', [API\GroupAPIController::class, 'dismissAsAdmin']);
    Route::get('users-blocked-by-me', [API\BlockUserAPIController::class, 'blockUsersByMe']);

    Route::get('notification/{notification}/read', [API\NotificationController::class, 'readNotification']);
    Route::get('notification/read-all', [API\NotificationController::class, 'readAllNotification']);

    /** Web Notifications */
    Route::put('update-web-notifications', [API\UserAPIController::class, 'updateNotification']);
    Route::put('update-player-id', [API\UserAPIController::class, 'updatePlayerId']);
    //set user custom status route
    Route::post('set-user-status', [API\UserAPIController::class, 'setUserCustomStatus'])->name('set-user-status');
    Route::get('clear-user-status', [API\UserAPIController::class, 'clearUserCustomStatus'])->name('clear-user-status');

    //report user
    Route::post('report-user', [API\ReportUserController::class, 'store'])->name('report-user.store');
});

// users
Route::group(['middleware' => ['permission:manage_users', 'auth', 'user.activated']], function () {
    Route::resource('users', UserController::class);
    Route::post('users/{user}/active-de-active', [UserController::class, 'activeDeActiveUser'])
        ->name('active-de-active-user');
    Route::post('users/{user}/update', [UserController::class, 'update']);
    Route::delete('users/{user}/archive', [UserController::class, 'archiveUser']);
    Route::post('users/restore', [UserController::class, 'restoreUser']);
    Route::get('users/{user}/login', [UserController::class, 'userImpersonateLogin']);
    Route::post('users/{user}/email-verified', [UserController::class, 'isEmailVerified'])->name('user.email-verified');
});

// roles
Route::group(['middleware' => ['permission:manage_roles', 'auth', 'user.activated']], function () {
    Route::resource('roles', RoleController::class)->except('update');
    Route::post('roles/{role}/update', [RoleController::class, 'update'])->name('roles.update');
});

// settings
Route::group(['middleware' => ['permission:manage_settings', 'auth', 'user.activated']], function () {
    Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::post('settings', [SettingsController::class, 'update'])->name('settings.update');
});

// reported-users
Route::group(['middleware' => ['permission:manage_reported_users', 'auth', 'user.activated']], function () {
    Route::resource('reported-users', ReportUserController::class);
});

// meetings
Route::group(['middleware' => ['permission:manage_meetings', 'auth', 'user.activated']], function () {
    Route::resource('meetings', MeetingController::class);
    Route::get('meetings/{meeting}/change-status', [MeetingController::class, 'changeMeetingStatus']);
});

Route::group(['middleware' => ['permission:manage_meetings', 'auth', 'user.activated']], function () {
    Route::get('member/meetings', [MeetingController::class, 'showMemberMeetings'])->name('meetings.member_index');
});

Route::group(['middleware' => ['web']], function () {
    Route::get('login/{provider}', [\App\Http\Controllers\Auth\SocialAuthController::class, 'redirect']);
    Route::get('login/{provider}/callback', [\App\Http\Controllers\Auth\SocialAuthController::class, 'callback']);
});


Route::resource('sliderManagers', App\Http\Controllers\slider_managerController::class);


Route::resource('userStories', App\Http\Controllers\user_storyController::class);


Route::resource('userStories', App\Http\Controllers\user_storyController::class);

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\Role;
use App\Models\User;
use App\Queries\UserDataTable;
use App\Repositories\UserRepository;
use Carbon\Carbon;
use DataTables;
use Exception;
use Hash;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;
use Response;

class UserController extends AppBaseController
{
    /** @var UserRepository */
    private $userRepository;

    public function __construct(UserRepository $userRepo)
    {
        $this->userRepository = $userRepo;
    }

    /**
     * @return Factory|View
     */
    public function getProfile()
    {
        return view('profile');
    }

    /**
     * Display a listing of the User.
     *
     * @param  Request  $request
     * @throws Exception
     * @return Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return Datatables::of((new UserDataTable())->get($request->only(['filter_user'])))->make(true);
        }
        $roles = Role::all()->pluck('name', 'id')->toArray();

        return view('users.index')->with([
            'roles' => $roles,
        ]);
    }

    /**
     * Show the form for creating a new User.
     *
     * @return Response
     */
    public function create()
    {
        $roles = Role::all()->pluck('name', 'id')->toArray();

        return view('users.create')->with(['roles' => $roles]);
    }

    /**
     * Store a newly created User in storage.
     *
     * @param  CreateUserRequest  $request
     *
     * @return Response
     */
    public function store(CreateUserRequest $request)
    {
        $input = $this->validateInput($request->all());

        $this->userRepository->store($input);

        return $this->sendSuccess('User saved successfully.');
    }

    /**
     * Display the specified User.
     * @param  User  $user
     *
     * @return Response
     */
    public function show(User $user)
    {
        $user->roles;
        $user = $user->apiObj();

        return view('users.show')->with('user', $user);
    }

    /**
     * Show the form for editing the specified User.
     *
     * @param  User  $user
     * @return Response
     */
    public function edit(User $user)
    {
        $user->roles;
        $user = $user->apiObj();

        return $this->sendResponse(['user' => $user], 'User retrieved successfully.');
    }

    /**
     * Update the specified User in storage.
     *
     * @param  User  $user
     * @param  UpdateUserRequest  $request
     *
     * @return Response
     */
    public function update(User $user, UpdateUserRequest $request)
    {
        if ($user->is_system) {
            return $this->sendError('You can not update system generated user.');
        }

        $input = $this->validateInput($request->all());
        $this->userRepository->update($input, $user->id);

        return $this->sendSuccess('User updated successfully.');
    }

    /**
     * @param  Request  $request
     *
     * @return JsonResponse
     */
    public function updateLanguage(Request $request)
    {
        $language = $request->get('languageName');

        /** @var User $user */
        $user = getLoggedInUser();
        $user->update(['language' => $language]);

        return $this->sendSuccess('Language updated successfully.');
    }

    /**
     * Remove the specified User from storage.
     *
     * @param User $user
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function archiveUser(User $user)
    {
        if ($user->is_system) {
            return $this->sendError('You can not archive system generated user.');
        }
        $this->userRepository->delete($user->id);

        return $this->sendSuccess('User archived successfully.');
    }

    /**
     * Remove the specified User from storage.
     *
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function restoreUser(Request $request)
    {
        $id = $request->get('id');
        $this->userRepository->restore($id);

        return $this->sendSuccess('User restored successfully.');
    }

    /**
     * Remove the specified User from storage.
     *
     * @param int $id
     *
     * @throws Exception
     *
     * @return JsonResponse
     */
    public function destroy($id)
    {
        $user = User::withTrashed()->whereId($id)->first();
        if ($user->is_system) {
            return $this->sendError('You can not delete system generated user.');
        }
        $this->userRepository->deleteUser($user->id);

        return $this->sendSuccess('User deleted successfully.');
    }

    /**
     * @param  User  $user
     *
     * @return JsonResponse
     */
    public function activeDeActiveUser(User $user)
    {
        $this->userRepository->checkUserItSelf($user->id);
        $this->userRepository->activeDeActiveUser($user->id);

        return $this->sendSuccess('User updated successfully.');
    }

    /**
     * @param $input
     *
     * @return mixed
     */
    public function validateInput($input)
    {
        if (isset($input['password']) && ! empty($input['password'])) {
            $input['password'] = Hash::make($input['password']);
        } else {
            unset($input['password']);
        }

        $input['is_active'] = (! empty($input['is_active'])) ? 1 : 0;

        return $input;
    }

    /**
     * @param  User  $user
     *
     * @return Application|RedirectResponse|Redirector
     */
    public function userImpersonateLogin(User $user)
    {
        Auth::user()->impersonate($user);
        
        if (\Auth::check() && \Auth::user()->hasPermissionTo('manage_conversations')){
            return redirect(url('/conversations'));
        }elseif (\Auth::check()) {
            if (\Auth::user()->getAllPermissions()->count() > 0) {
                $url = getPermissionWiseRedirectTo(\Auth::user()->getAllPermissions()->first());

                return redirect(url($url));
            }else{
                return redirect(url('/conversations'));
            }
        }
    }

    /**
     * @return Application|RedirectResponse|Redirector
     */
    public function userImpersonateLogout()
    {
        Auth::user()->leaveImpersonation();

        return redirect(url('/conversations'));
    }
    
    /**
     * @param  User  $user
     *
     * @return JsonResponse
     */
    public function isEmailVerified(User $user)
    {
        $emailVerified = $user->email_verified_at == null ? Carbon::now() : null;
        $user->update(['email_verified_at' => $emailVerified]);

        return $this->sendSuccess('Email Verified successfully.');
    }
}

resources/views/users/create.blade.php
<div id="create_user_modal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{{ __('messages.new_user') }}</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="form-group col-sm-12">
                <div class="" id="validationErrorsBox"></div>
            </div>
            {!! Form::open(['id'=>'createUserForm', 'method' => 'POST']) !!}
            <div class="modal-body">
                @include('users.fields')
            </div>
            {!! Form::close() !!}
        </div>

    </div>
</div>

resources/views/users/edit.blade.php
<div id="edit_user_modal" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{{ __('messages.edit_user') }}</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            {!! Form::open(['id'=>'editUserForm', 'method' => 'POST', 'files' => true]) !!}
            {!! Form::hidden('id','',['id' => 'edit_user_id']) !!}
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="alert alert-danger" style="display: none" id="editValidationErrorsBox"></div>
                    </div>
                    <div class="col-sm-12 d-flex flex-sm-row flex-column align-items-center">
                        <div class="form-group">
                            <div class="profile__inner m-auto">
                                <div class="text-center profile__img-wrapper">
                                    <img src="{{ isset($user->photo_url) ? $user->photo_url : getDefaultAvatar() }}"
                                         alt="" id="edit_upload-photo-img">
                                </div>
                                <div class="text-center mt-2 user__upload-btn">
                                    <label class="btn profile__update-label">
                                        {{ __('messages.upload_photo') }}
                                        <input id="edit_upload-photo" class="d-none" name="photo" type="file">
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-lg-6 login-group__sub-title">
                                {!! Form::label('member_no', __('messages.member_no') ) !!}<span class="red">*</span>
                                {!! Form::text('member_no', null, ['class' => 'form-control login-group__input', 'id' => 'member_no']) !!}
                            </div>
                            <!-- Name Field -->
                            
                            <div class="form-group col-lg-6 login-group__sub-title">
                                {!! Form::label('name', __('messages.full_name') ) !!}<span class="red">*</span>
                                {!! Form::text('name', null, ['class' => 'form-control login-group__input', 'id' => 'edit_name', 'required']) !!}
                            </div>

                            <!-- Phone Field -->
                            <div class="form-group col-lg-6 login-group__sub-title">
                                {!! Form::label('phone', __('messages.phone') ) !!}
                                {!! Form::text('phone', null, ['class' => 'form-control login-group__input', 'id' => 'edit_phone']) !!}
                            </div>

                            <!-- Email Field -->
                            <div class="form-group col-12 login-group__sub-title">
                                {!! Form::label('email', __('messages.email') ) !!}<span class="red">*</span>
                                {!! Form::email('email', null, ['class' => 'form-control login-group__input', 'id' => 'edit_email',  'required']) !!}
                            </div>
                        </div>
                    </div>
                    <!-- Bio Field -->
                    <div class="form-group login-group__sub-title col-12">
                        {!! Form::label('bio', __('messages.bio') ) !!}
                        {!! Form::textarea('about', null, ['class' => 'form-control user__bio login-group__input', 'rows' => 3, 'id' => 'edit_about']) !!}
                    </div>
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="form-group  col-sm-6">
                                <label class="login-group__sub-title">{{ __('messages.gender') }}</label><span class="red">*</span>
                                <div class="d-flex login-group__input align-items-center">
                                    <div class="custom-control custom-radio mx-2">
                                        <input type="radio" class="custom-control-input" id="edit_male" name="gender"
                                                value="{{ \App\Models\User::MALE }}" required> <label class="custom-control-label"
                                                for="edit_male">
                                            {{ __('messages.male') }}
                                        </label>
                                    </div>
                                    <div class="custom-control custom-radio mx-2">
                                        <input type="radio" class="custom-control-input" id="edit_female" name="gender"
                                               value="{{ \App\Models\User::FEMALE }}" required> <label class="custom-control-label"
                                                                                              for="edit_female">
                                            {{ __('messages.female') }}
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-sm-6">
                                <label class="login-group__sub-title">{{ __('messages.group.privacy') }}</label><span class="red">*</span>
                                <div class="d-flex login-group__input align-items-center">
                                    <div class="custom-control custom-radio mx-2">
                                        <input type="radio" class="custom-control-input" id="editPrivacyPrivate"
                                               name="privacy" value="0" required> <label class="custom-control-label"
                                                                                for="editPrivacyPrivate">
                                            {{ __('messages.group.private') }}
                                            <i class="fa fa-question-circle ml-2 question-type-open cursor-pointer"
                                               data-toggle="tooltip" data-placement="top" title=""
                                               data-original-title="All group members can send messages into the group."></i>
                                        </label>
                                    </div>
                                    <div class="custom-control custom-radio mx-2">
                                        <input type="radio" class="custom-control-input" id="editPrivacyPublic"
                                               name="privacy" value="1" required> <label class="custom-control-label"
                                                                                for="editPrivacyPublic">
                                            {{ __('messages.group.public') }}
                                            <i class="fa fa-question-circle ml-2 question-type-open cursor-pointer"
                                               data-toggle="tooltip" data-placement="top" title=""
                                               data-original-title="All group members can send messages into the group."></i>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="row">
                            <!-- Is Active Field -->
                            <div class="form-group col-sm-6 login-group__sub-title">
                                {!! Form::label('is_active', __('messages.is_active') ) !!}<span class="red">*</span>
                                {!! Form::select('is_active', [1 => 'Active', 0 => 'In Active'], (isset($user->is_active)) ? $user->is_active : [],  ['class' => 'form-control login-group__input', 'id' => 'edit_is_active',  'required']) !!}
                            </div>
                            <!-- Role Field -->
                            <div class="form-group col-sm-6 login-group__sub-title">
                                {!! Form::label('role', __('messages.role') ) !!}<span class="red">*</span>
                                {!! Form::select('role_id', $roles, (isset($user->role_id)) ? $user->role_id : [],  ['class' => 'form-control login-group__input','placeholder' => 'Select Role', 'id' => 'edit_role_id']) !!}
                            </div>
                        </div>
                    </div>
                    <!-- Submit Field -->
                    <div class="text-left form-group mb-0 col-sm-12">
                        {!! Form::submit(__('messages.save'), ['class' => 'btn btn-primary', 'id' => 'editBtnSave']) !!}
                        <button type="button" class="btn btn-secondary ml-1"
                                data-dismiss="modal">{{ __('messages.cancel') }}</button>
                    </div>
                </div>
            </div>
            {!! Form::close() !!}
        </div>

    </div>
</div>

resources/views/users/index.blade.php
@extends('layouts.app')
@section('title')
    {{ __('messages.users') }}
@endsection
@section('page_css')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/dataTable.min.css') }}"/>
@endsection
@section('css')
    <link rel="stylesheet" href="{{ mix('assets/css/admin_panel.css') }}">
@endsection
@section('content')
    <div class="container-fluid page__container">
        <div class="animated fadeIn main-table">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header page-header flex-wrap">
                             <div class="pull-left page__heading mr-3 my-2">
                                 {{ __('messages.users') }}
                             </div>
                             <div class="filter-container flex-wrap">
                                 <div class="mr-2 my-2 user-select2">
                                     {!!Form::select('drp_users', \App\Models\User::FILTER_ARRAY, \App\Models\User::FILTER_ALL, ['id' => 'filter_user','class'=>'form-control','style'=>'min-width:150px;'])  !!}
                                 </div>
                                 <button type="button" class="my-2 pull-right btn btn-primary filter-container__btn" data-toggle="modal" data-target="#create_user_modal">{{ __('messages.new_user') }}</button>
                             </div>
                         </div>
                         <div class="card-body">
                             @include('users.table')
                              <div class="pull-right mr-3">

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
    @include('users.create')
    @include('users.edit')
    @include('users.templates.action_icons')
@endsection
@section('page_js')
    <script type="text/javascript" src="{{ asset('js/dataTable.min.js') }}"></script>
@endsection
@section('scripts')
    <script>
        let createUserUrl = "{{ route('users.store') }}";
        let usersUrl = "{{ url('users') }}";
        let defaultImageAvatar = "{{ getDefaultAvatar() }}/";
    </script>
    <script src="{{ mix('assets/js/admin/users/user.js') }}"></script>
    <script src="{{ mix('assets/js/admin/users/edit_user.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/custom-datatables.js') }}"></script>
@endsection

resources/views/users/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-bordered" id="users_table">
        <thead>
        <th>{{ __('messages.user') }}</th>
        <th>{{ __('messages.role') }}</th>
        <th>{{ __('messages.group.privacy') }}</th>
        <th>{{ __('messages.email_verified') }}</th>
        <th>{{ __('messages.is_active') }}</th>
        <th>{{ __('messages.impersonate') }}</th>
        <th>{{ __('messages.lv') }}</th>
        <th>{{ __('messages.action') }}</th>
        </thead>
        <tbody></tbody>
    </table>
</div>