routes/web.php
use App\Http\Controllers\UserController;
use Database\Seeders\CreatePermissionSeeder;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.index');
});

Route::get('upgrade-to-v3-4-0', function () {
    try {
        \Artisan::call('migrate', [
            '--path'  => '/database/migrations/2020_10_19_133700_move_all_existing_devices_to_new_table.php',
            '--force' => true,
        ]);

        return 'You are successfully migrated to v3.4.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Route::get('/upgrade-to-v4-3-0', function () {
    try {
        Artisan::call('db:seed', ['--class' => 'CreatePermissionSeeder']);

        return 'You are successfully seeded to v4.3.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Route::get('upgrade-to-v5-0-0', function () {
    try {
        \Artisan::call('migrate', [
            '--path'  => '/database/migrations/2021_07_12_000000_add_uuid_to_failed_jobs_table.php',
            '--force' => true,
        ]);

        return 'You are successfully migrated to v5.0.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Auth::routes();
Route::get('activate', [AuthController::class, 'verifyAccount']);

Route::get('/home', [HomeController::class, 'index']);
Route::post('update-language', [UserController::class, 'updateLanguage'])->middleware('auth');

// Impersonate Logout
Route::get('/users/impersonate-logout', [UserController::class, 'userImpersonateLogout'])->name('impersonate.userLogout');

Route::group(['middleware' => ['user.activated', 'auth']], function () {
    //view routes
    Route::get('/conversations',
        [ChatController::class, 'index'])->name('conversations')->middleware('permission:manage_conversations');
    Route::get('profile', [UserController::class, 'getProfile']);
    Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);

    //get all user list for chat
    Route::get('users-list', [API\UserAPIController::class, 'getUsersList']);
    Route::get('get-users', [API\UserAPIController::class, 'getUsers']);
    Route::delete('remove-profile-image', [API\UserAPIController::class, 'removeProfileImage']);
    /** Change password */
    Route::post('change-password', [API\UserAPIController::class, 'changePassword']);
    Route::get('conversations/{ownerId}/archive-chat', [API\UserAPIController::class, 'archiveChat']);

    Route::get('get-profile', [API\UserAPIController::class, 'getProfile']);
    Route::post('profile', [API\UserAPIController::class, 'updateProfile'])->name('update.profile');
    Route::post('update-last-seen', [API\UserAPIController::class, 'updateLastSeen']);

    Route::post('send-message',
        [API\ChatAPIController::class, 'sendMessage'])->name('conversations.store')->middleware('sendMessage');
    Route::get('users/{id}/conversation', [API\UserAPIController::class, 'getConversation']);
    Route::get('conversations-list', [API\ChatAPIController::class, 'getLatestConversations']);
    Route::get('archive-conversations', [API\ChatAPIController::class, 'getArchiveConversations']);
    Route::post('read-message', [API\ChatAPIController::class, 'updateConversationStatus']);
    Route::post('file-upload', [API\ChatAPIController::class, 'addAttachment'])->name('file-upload');
    Route::post('image-upload', [API\ChatAPIController::class, 'imageUpload'])->name('image-upload');
    Route::get('conversations/{userId}/delete', [API\ChatAPIController::class, 'deleteConversation']);
    Route::post('conversations/message/{conversation}/delete', [API\ChatAPIController::class, 'deleteMessage']);
    Route::post('conversations/{conversation}/delete', [API\ChatAPIController::class, 'deleteMessageForEveryone']);
    Route::get('/conversations/{conversation}', [API\ChatAPIController::class, 'show']);
    Route::post('send-chat-request', [API\ChatAPIController::class, 'sendChatRequest'])->name('send-chat-request');
    Route::post('accept-chat-request',
        [API\ChatAPIController::class, 'acceptChatRequest'])->name('accept-chat-request');
    Route::post('decline-chat-request',
        [API\ChatAPIController::class, 'declineChatRequest'])->name('decline-chat-request');

    /** Web Notifications */
    Route::put('update-web-notifications', [API\UserAPIController::class, 'updateNotification']);

    /** BLock-Unblock User */
    Route::put('users/{user}/block-unblock', [API\BlockUserAPIController::class, 'blockUnblockUser']);
    Route::get('blocked-users', [API\BlockUserAPIController::class, 'blockedUsers']);

    /** My Contacts */
    Route::get('my-contacts', [API\UserAPIController::class, 'myContacts'])->name('my-contacts');

    /** Groups API */
    Route::post('groups', [API\GroupAPIController::class, 'create']);
    Route::post('groups/{group}', [API\GroupAPIController::class, 'update']);
    Route::get('groups', [API\GroupAPIController::class, 'index']);
    Route::get('groups/{group}', [API\GroupAPIController::class, 'show']);
    Route::put('groups/{group}/add-members', [API\GroupAPIController::class, 'addMembers']);
    Route::delete('groups/{group}/members/{user}', [API\GroupAPIController::class, 'removeMemberFromGroup']);
    Route::delete('groups/{group}/leave', [API\GroupAPIController::class, 'leaveGroup']);
    Route::delete('groups/{group}/remove', [API\GroupAPIController::class, 'removeGroup']);
    Route::put('groups/{group}/members/{user}/make-admin', [API\GroupAPIController::class, 'makeAdmin']);
    Route::put('groups/{group}/members/{user}/dismiss-as-admin', [API\GroupAPIController::class, 'dismissAsAdmin']);
    Route::get('users-blocked-by-me', [API\BlockUserAPIController::class, 'blockUsersByMe']);

    Route::get('notification/{notification}/read', [API\NotificationController::class, 'readNotification']);
    Route::get('notification/read-all', [API\NotificationController::class, 'readAllNotification']);

    /** Web Notifications */
    Route::put('update-web-notifications', [API\UserAPIController::class, 'updateNotification']);
    Route::put('update-player-id', [API\UserAPIController::class, 'updatePlayerId']);
    //set user custom status route
    Route::post('set-user-status', [API\UserAPIController::class, 'setUserCustomStatus'])->name('set-user-status');
    Route::get('clear-user-status', [API\UserAPIController::class, 'clearUserCustomStatus'])->name('clear-user-status');

    //report user
    Route::post('report-user', [API\ReportUserController::class, 'store'])->name('report-user.store');
});

// users
Route::group(['middleware' => ['permission:manage_users', 'auth', 'user.activated']], function () {
    Route::resource('users', UserController::class);
    Route::post('users/{user}/active-de-active', [UserController::class, 'activeDeActiveUser'])
        ->name('active-de-active-user');
    Route::post('users/{user}/update', [UserController::class, 'update']);
    Route::delete('users/{user}/archive', [UserController::class, 'archiveUser']);
    Route::post('users/restore', [UserController::class, 'restoreUser']);
    Route::get('users/{user}/login', [UserController::class, 'userImpersonateLogin']);
    Route::post('users/{user}/email-verified', [UserController::class, 'isEmailVerified'])->name('user.email-verified');
});

// roles
Route::group(['middleware' => ['permission:manage_roles', 'auth', 'user.activated']], function () {
    Route::resource('roles', RoleController::class)->except('update');
    Route::post('roles/{role}/update', [RoleController::class, 'update'])->name('roles.update');
});

// settings
Route::group(['middleware' => ['permission:manage_settings', 'auth', 'user.activated']], function () {
    Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::post('settings', [SettingsController::class, 'update'])->name('settings.update');
});

// reported-users
Route::group(['middleware' => ['permission:manage_reported_users', 'auth', 'user.activated']], function () {
    Route::resource('reported-users', ReportUserController::class);
});

// meetings
Route::group(['middleware' => ['permission:manage_meetings', 'auth', 'user.activated']], function () {
    Route::resource('meetings', MeetingController::class);
    Route::get('meetings/{meeting}/change-status', [MeetingController::class, 'changeMeetingStatus']);
});

Route::group(['middleware' => ['permission:manage_meetings', 'auth', 'user.activated']], function () {
    Route::get('member/meetings', [MeetingController::class, 'showMemberMeetings'])->name('meetings.member_index');
});

Route::group(['middleware' => ['web']], function () {
    Route::get('login/{provider}', [\App\Http\Controllers\Auth\SocialAuthController::class, 'redirect']);
    Route::get('login/{provider}/callback', [\App\Http\Controllers\Auth\SocialAuthController::class, 'callback']);
});


Route::resource('sliderManagers', App\Http\Controllers\slider_managerController::class);


Route::resource('userStories', App\Http\Controllers\user_storyController::class);


Route::resource('userStories', App\Http\Controllers\user_storyController::class);


Route::resource('upgradeInfos', App\Http\Controllers\upgrade_infoController::class);


Route::resource('walletLogs', App\Http\Controllers\wallet_logController::class);


Route::resource('wallets', App\Http\Controllers\walletController::class);


Route::resource('transToBanks', App\Http\Controllers\trans_to_bankController::class);

app/Models/trans_to_bank.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

use DateTimeInterface;

/**
 * Class trans_to_bank
 * @package App\Models
 * @version November 15, 2021, 3:01 am UTC
 *
 * @property integer $user_id
 * @property string $bank_no
 * @property string $bank_name
 * @property string $sub_bank_name
 * @property string $account_name
 * @property string $account_no
 * @property string $address
 * @property string $contact_name
 * @property string $id_no
 * @property string $paper_photo
 * @property integer $status
 */
class trans_to_bank extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'trans_to_bank';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'user_id',
        'bank_no',
        'bank_name',
        'sub_bank_name',
        'account_name',
        'account_no',
        'address',
        'contact_name',
        'id_no',
        'paper_photo',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'bank_no' => 'string',
        'bank_name' => 'string',
        'sub_bank_name' => 'string',
        'account_name' => 'string',
        'account_no' => 'string',
        'address' => 'string',
        'contact_name' => 'string',
        'id_no' => 'string',
        'paper_photo' => 'string',
        'status' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        // 'user_id' => 'required|integer',
        // 'bank_no' => 'nullable|string|max:191',
        // 'bank_name' => 'required|string|max:191',
        // 'sub_bank_name' => 'required|string|max:191',
        // 'account_name' => 'required|string|max:191',
        // 'account_no' => 'required|string|max:191',
        // 'address' => 'required|string|max:191',
        // 'contact_name' => 'required|string|max:191',
        // 'id_no' => 'required|string|max:191',
        // 'paper_photo' => 'required|string',
        // 'status' => 'required|integer',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    

    
    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/trans_to_bankController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\trans_to_bankDataTable;
use App\Http\Requests;
use App\Http\Requests\Createtrans_to_bankRequest;
use App\Http\Requests\Updatetrans_to_bankRequest;
use App\Repositories\trans_to_bankRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class trans_to_bankController extends AppBaseController
{
    /** @var  trans_to_bankRepository */
    private $transToBankRepository;

    public function __construct(trans_to_bankRepository $transToBankRepo)
    {
        $this->transToBankRepository = $transToBankRepo;
    }

    /**
     * Display a listing of the trans_to_bank.
     *
     * @param trans_to_bankDataTable $transToBankDataTable
     * @return Response
     */
    public function index(trans_to_bankDataTable $transToBankDataTable)
    {
        return $transToBankDataTable->render('trans_to_banks.index');
    }

    /**
     * Show the form for creating a new trans_to_bank.
     *
     * @return Response
     */
    public function create()
    {
        return view('trans_to_banks.create');
    }

    /**
     * Store a newly created trans_to_bank in storage.
     *
     * @param Createtrans_to_bankRequest $request
     *
     * @return Response
     */
    public function store(Createtrans_to_bankRequest $request)
    {
        $input = $request->all();

        $transToBank = $this->transToBankRepository->create($input);

        Flash::success('Trans To Bank saved successfully.');

        return redirect(route('transToBanks.index'));
    }

    /**
     * Display the specified trans_to_bank.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $transToBank = $this->transToBankRepository->find($id);

        if (empty($transToBank)) {
            Flash::error('Trans To Bank not found');

            return redirect(route('transToBanks.index'));
        }

        return view('trans_to_banks.show')->with('transToBank', $transToBank);
    }

    /**
     * Show the form for editing the specified trans_to_bank.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $transToBank = $this->transToBankRepository->find($id);

        if (empty($transToBank)) {
            Flash::error('Trans To Bank not found');

            return redirect(route('transToBanks.index'));
        }

        return view('trans_to_banks.edit')->with('transToBank', $transToBank);
    }

    /**
     * Update the specified trans_to_bank in storage.
     *
     * @param  int              $id
     * @param Updatetrans_to_bankRequest $request
     *
     * @return Response
     */
    public function update($id, Updatetrans_to_bankRequest $request)
    {
        $transToBank = $this->transToBankRepository->find($id);

        if (empty($transToBank)) {
            Flash::error('Trans To Bank not found');

            return redirect(route('transToBanks.index'));
        }

        $transToBank = $this->transToBankRepository->update($request->all(), $id);

        Flash::success('Trans To Bank updated successfully.');

        return redirect(route('transToBanks.index'));
    }

    /**
     * Remove the specified trans_to_bank from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $transToBank = $this->transToBankRepository->find($id);

        if (empty($transToBank)) {
            Flash::error('Trans To Bank not found');

            return redirect(route('transToBanks.index'));
        }

        $this->transToBankRepository->delete($id);

        Flash::success('Trans To Bank deleted successfully.');

        return redirect(route('transToBanks.index'));
    }
}

resources/views/trans_to_banks/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('transToBanks.index') !!}">Trans To Bank</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Trans To Bank</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'transToBanks.store']) !!}

                                   @include('trans_to_banks.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/trans_to_banks/datatables_actions.blade.php
{!! Form::open(['route' => ['transToBanks.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('transToBanks.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('transToBanks.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/trans_to_banks/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('transToBanks.index') !!}">Trans To Bank</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Trans To Bank</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($transToBank, ['route' => ['transToBanks.update', $transToBank->id], 'method' => 'patch']) !!}

                              @include('trans_to_banks.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/trans_to_banks/fields.blade.php
<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Bank No Field -->
<div class="form-group col-sm-6">
    {!! Form::label('bank_no', 'Bank No:') !!}
    {!! Form::text('bank_no', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Bank Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('bank_name', 'Bank Name:') !!}
    {!! Form::text('bank_name', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Sub Bank Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('sub_bank_name', 'Sub Bank Name:') !!}
    {!! Form::text('sub_bank_name', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Account Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('account_name', 'Account Name:') !!}
    {!! Form::text('account_name', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Account No Field -->
<div class="form-group col-sm-6">
    {!! Form::label('account_no', 'Account No:') !!}
    {!! Form::text('account_no', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-6">
    {!! Form::label('address', 'Address:') !!}
    {!! Form::text('address', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Contact Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('contact_name', 'Contact Name:') !!}
    {!! Form::text('contact_name', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Id No Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_no', 'Id No:') !!}
    {!! Form::text('id_no', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Paper Photo Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('paper_photo', 'Paper Photo:') !!}
    {!! Form::textarea('paper_photo', null, ['class' => 'form-control']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::number('status', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('transToBanks.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/trans_to_banks/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Trans To Banks</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             trans_to_banks
                             <a class="pull-right" href="{{ route('transToBanks.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('trans_to_banks.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/trans_to_banks/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('transToBanks.index') }}">Trans To Bank</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('transToBanks.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('trans_to_banks.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/trans_to_banks/show_fields.blade.php
<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{{ $transToBank->user_id }}</p>
</div>

<!-- Bank No Field -->
<div class="form-group">
    {!! Form::label('bank_no', 'Bank No:') !!}
    <p>{{ $transToBank->bank_no }}</p>
</div>

<!-- Bank Name Field -->
<div class="form-group">
    {!! Form::label('bank_name', 'Bank Name:') !!}
    <p>{{ $transToBank->bank_name }}</p>
</div>

<!-- Sub Bank Name Field -->
<div class="form-group">
    {!! Form::label('sub_bank_name', 'Sub Bank Name:') !!}
    <p>{{ $transToBank->sub_bank_name }}</p>
</div>

<!-- Account Name Field -->
<div class="form-group">
    {!! Form::label('account_name', 'Account Name:') !!}
    <p>{{ $transToBank->account_name }}</p>
</div>

<!-- Account No Field -->
<div class="form-group">
    {!! Form::label('account_no', 'Account No:') !!}
    <p>{{ $transToBank->account_no }}</p>
</div>

<!-- Address Field -->
<div class="form-group">
    {!! Form::label('address', 'Address:') !!}
    <p>{{ $transToBank->address }}</p>
</div>

<!-- Contact Name Field -->
<div class="form-group">
    {!! Form::label('contact_name', 'Contact Name:') !!}
    <p>{{ $transToBank->contact_name }}</p>
</div>

<!-- Id No Field -->
<div class="form-group">
    {!! Form::label('id_no', 'Id No:') !!}
    <p>{{ $transToBank->id_no }}</p>
</div>

<!-- Paper Photo Field -->
<div class="form-group">
    {!! Form::label('paper_photo', 'Paper Photo:') !!}
    <p>{{ $transToBank->paper_photo }}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>{{ $transToBank->status }}</p>
</div>

resources/views/trans_to_banks/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush