routes/web.php
use App\Http\Controllers\UserController;
use Database\Seeders\CreatePermissionSeeder;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.index');
});

Route::get('upgrade-to-v3-4-0', function () {
    try {
        \Artisan::call('migrate', [
            '--path'  => '/database/migrations/2020_10_19_133700_move_all_existing_devices_to_new_table.php',
            '--force' => true,
        ]);

        return 'You are successfully migrated to v3.4.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Route::get('/upgrade-to-v4-3-0', function () {
    try {
        Artisan::call('db:seed', ['--class' => 'CreatePermissionSeeder']);

        return 'You are successfully seeded to v4.3.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Route::get('upgrade-to-v5-0-0', function () {
    try {
        \Artisan::call('migrate', [
            '--path'  => '/database/migrations/2021_07_12_000000_add_uuid_to_failed_jobs_table.php',
            '--force' => true,
        ]);

        return 'You are successfully migrated to v5.0.0';
    } catch (Exception $exception) {
        return $exception->getMessage();
    }
});

Auth::routes();
Route::get('activate', [AuthController::class, 'verifyAccount']);

Route::get('/home', [HomeController::class, 'index']);
Route::post('update-language', [UserController::class, 'updateLanguage'])->middleware('auth');

// Impersonate Logout
Route::get('/users/impersonate-logout', [UserController::class, 'userImpersonateLogout'])->name('impersonate.userLogout');

Route::group(['middleware' => ['user.activated', 'auth']], function () {
    //view routes
    Route::get('/conversations',
        [ChatController::class, 'index'])->name('conversations')->middleware('permission:manage_conversations');
    Route::get('profile', [UserController::class, 'getProfile']);
    Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);

    //get all user list for chat
    Route::get('users-list', [API\UserAPIController::class, 'getUsersList']);
    Route::get('get-users', [API\UserAPIController::class, 'getUsers']);
    Route::delete('remove-profile-image', [API\UserAPIController::class, 'removeProfileImage']);
    /** Change password */
    Route::post('change-password', [API\UserAPIController::class, 'changePassword']);
    Route::get('conversations/{ownerId}/archive-chat', [API\UserAPIController::class, 'archiveChat']);

    Route::get('get-profile', [API\UserAPIController::class, 'getProfile']);
    Route::post('profile', [API\UserAPIController::class, 'updateProfile'])->name('update.profile');
    Route::post('update-last-seen', [API\UserAPIController::class, 'updateLastSeen']);

    Route::post('send-message',
        [API\ChatAPIController::class, 'sendMessage'])->name('conversations.store')->middleware('sendMessage');
    Route::get('users/{id}/conversation', [API\UserAPIController::class, 'getConversation']);
    Route::get('conversations-list', [API\ChatAPIController::class, 'getLatestConversations']);
    Route::get('archive-conversations', [API\ChatAPIController::class, 'getArchiveConversations']);
    Route::post('read-message', [API\ChatAPIController::class, 'updateConversationStatus']);
    Route::post('file-upload', [API\ChatAPIController::class, 'addAttachment'])->name('file-upload');
    Route::post('image-upload', [API\ChatAPIController::class, 'imageUpload'])->name('image-upload');
    Route::get('conversations/{userId}/delete', [API\ChatAPIController::class, 'deleteConversation']);
    Route::post('conversations/message/{conversation}/delete', [API\ChatAPIController::class, 'deleteMessage']);
    Route::post('conversations/{conversation}/delete', [API\ChatAPIController::class, 'deleteMessageForEveryone']);
    Route::get('/conversations/{conversation}', [API\ChatAPIController::class, 'show']);
    Route::post('send-chat-request', [API\ChatAPIController::class, 'sendChatRequest'])->name('send-chat-request');
    Route::post('accept-chat-request',
        [API\ChatAPIController::class, 'acceptChatRequest'])->name('accept-chat-request');
    Route::post('decline-chat-request',
        [API\ChatAPIController::class, 'declineChatRequest'])->name('decline-chat-request');

    /** Web Notifications */
    Route::put('update-web-notifications', [API\UserAPIController::class, 'updateNotification']);

    /** BLock-Unblock User */
    Route::put('users/{user}/block-unblock', [API\BlockUserAPIController::class, 'blockUnblockUser']);
    Route::get('blocked-users', [API\BlockUserAPIController::class, 'blockedUsers']);

    /** My Contacts */
    Route::get('my-contacts', [API\UserAPIController::class, 'myContacts'])->name('my-contacts');

    /** Groups API */
    Route::post('groups', [API\GroupAPIController::class, 'create']);
    Route::post('groups/{group}', [API\GroupAPIController::class, 'update']);
    Route::get('groups', [API\GroupAPIController::class, 'index']);
    Route::get('groups/{group}', [API\GroupAPIController::class, 'show']);
    Route::put('groups/{group}/add-members', [API\GroupAPIController::class, 'addMembers']);
    Route::delete('groups/{group}/members/{user}', [API\GroupAPIController::class, 'removeMemberFromGroup']);
    Route::delete('groups/{group}/leave', [API\GroupAPIController::class, 'leaveGroup']);
    Route::delete('groups/{group}/remove', [API\GroupAPIController::class, 'removeGroup']);
    Route::put('groups/{group}/members/{user}/make-admin', [API\GroupAPIController::class, 'makeAdmin']);
    Route::put('groups/{group}/members/{user}/dismiss-as-admin', [API\GroupAPIController::class, 'dismissAsAdmin']);
    Route::get('users-blocked-by-me', [API\BlockUserAPIController::class, 'blockUsersByMe']);

    Route::get('notification/{notification}/read', [API\NotificationController::class, 'readNotification']);
    Route::get('notification/read-all', [API\NotificationController::class, 'readAllNotification']);

    /** Web Notifications */
    Route::put('update-web-notifications', [API\UserAPIController::class, 'updateNotification']);
    Route::put('update-player-id', [API\UserAPIController::class, 'updatePlayerId']);
    //set user custom status route
    Route::post('set-user-status', [API\UserAPIController::class, 'setUserCustomStatus'])->name('set-user-status');
    Route::get('clear-user-status', [API\UserAPIController::class, 'clearUserCustomStatus'])->name('clear-user-status');

    //report user
    Route::post('report-user', [API\ReportUserController::class, 'store'])->name('report-user.store');
});

// users
Route::group(['middleware' => ['permission:manage_users', 'auth', 'user.activated']], function () {
    Route::resource('users', UserController::class);
    Route::post('users/{user}/active-de-active', [UserController::class, 'activeDeActiveUser'])
        ->name('active-de-active-user');
    Route::post('users/{user}/update', [UserController::class, 'update']);
    Route::delete('users/{user}/archive', [UserController::class, 'archiveUser']);
    Route::post('users/restore', [UserController::class, 'restoreUser']);
    Route::get('users/{user}/login', [UserController::class, 'userImpersonateLogin']);
    Route::post('users/{user}/email-verified', [UserController::class, 'isEmailVerified'])->name('user.email-verified');
});

// roles
Route::group(['middleware' => ['permission:manage_roles', 'auth', 'user.activated']], function () {
    Route::resource('roles', RoleController::class)->except('update');
    Route::post('roles/{role}/update', [RoleController::class, 'update'])->name('roles.update');
});

// settings
Route::group(['middleware' => ['permission:manage_settings', 'auth', 'user.activated']], function () {
    Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::post('settings', [SettingsController::class, 'update'])->name('settings.update');
});

// reported-users
Route::group(['middleware' => ['permission:manage_reported_users', 'auth', 'user.activated']], function () {
    Route::resource('reported-users', ReportUserController::class);
});

// meetings
Route::group(['middleware' => ['permission:manage_meetings', 'auth', 'user.activated']], function () {
    Route::resource('meetings', MeetingController::class);
    Route::get('meetings/{meeting}/change-status', [MeetingController::class, 'changeMeetingStatus']);
});

Route::group(['middleware' => ['permission:manage_meetings', 'auth', 'user.activated']], function () {
    Route::get('member/meetings', [MeetingController::class, 'showMemberMeetings'])->name('meetings.member_index');
});

Route::group(['middleware' => ['web']], function () {
    Route::get('login/{provider}', [\App\Http\Controllers\Auth\SocialAuthController::class, 'redirect']);
    Route::get('login/{provider}/callback', [\App\Http\Controllers\Auth\SocialAuthController::class, 'callback']);
});


Route::resource('sliderManagers', App\Http\Controllers\slider_managerController::class);


Route::resource('userStories', App\Http\Controllers\user_storyController::class);


Route::resource('userStories', App\Http\Controllers\user_storyController::class);


Route::resource('upgradeInfos', App\Http\Controllers\upgrade_infoController::class);


Route::resource('walletLogs', App\Http\Controllers\wallet_logController::class);


Route::resource('wallets', App\Http\Controllers\walletController::class);


Route::resource('transToBanks', App\Http\Controllers\trans_to_bankController::class);

app/Models/upgrade_info.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

use DateTimeInterface;

/**
 * Class upgrade_info
 * @package App\Models
 * @version November 14, 2021, 12:34 pm UTC
 *
 * @property string $company_name
 * @property string $address
 * @property string $contact_name
 * @property string $email
 * @property string $phone
 * @property string $ref_id
 * @property string $place_id
 */
class upgrade_info extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'upgrade_info';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'company_name',
        'address',
        'contact_name',
        'email',
        'phone',
        'ref_id',
        'place_id',
        'status',
        'user_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'company_name' => 'string',
        'address' => 'string',
        'contact_name' => 'string',
        'email' => 'string',
        'phone' => 'string',
        'ref_id' => 'string',
        'place_id' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        // 'company_name' => 'required|string|max:191',
        // 'address' => 'nullable|string|max:191',
        // 'contact_name' => 'required|string|max:191',
        // 'email' => 'required|string|max:191',
        // 'phone' => 'required|string|max:191',
        // 'ref_id' => 'required|string|max:191',
        // 'place_id' => 'nullable|string|max:191',
        // 'created_at' => 'nullable',
        // 'updated_at' => 'nullable',
        // 'deleted_at' => 'nullable'
    ];

    

    
    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/upgrade_infoController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\upgrade_infoDataTable;
use App\Http\Requests;
use App\Http\Requests\Createupgrade_infoRequest;
use App\Http\Requests\Updateupgrade_infoRequest;
use App\Repositories\upgrade_infoRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class upgrade_infoController extends AppBaseController
{
    /** @var  upgrade_infoRepository */
    private $upgradeInfoRepository;

    public function __construct(upgrade_infoRepository $upgradeInfoRepo)
    {
        $this->upgradeInfoRepository = $upgradeInfoRepo;
    }

    /**
     * Display a listing of the upgrade_info.
     *
     * @param upgrade_infoDataTable $upgradeInfoDataTable
     * @return Response
     */
    public function index(upgrade_infoDataTable $upgradeInfoDataTable)
    {
        return $upgradeInfoDataTable->render('upgrade_infos.index');
    }

    /**
     * Show the form for creating a new upgrade_info.
     *
     * @return Response
     */
    public function create()
    {
        return view('upgrade_infos.create');
    }

    /**
     * Store a newly created upgrade_info in storage.
     *
     * @param Createupgrade_infoRequest $request
     *
     * @return Response
     */
    public function store(Createupgrade_infoRequest $request)
    {
        $input = $request->all();

        $upgradeInfo = $this->upgradeInfoRepository->create($input);

        Flash::success('Upgrade Info saved successfully.');

        return redirect(route('upgradeInfos.index'));
    }

    /**
     * Display the specified upgrade_info.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $upgradeInfo = $this->upgradeInfoRepository->find($id);

        if (empty($upgradeInfo)) {
            Flash::error('Upgrade Info not found');

            return redirect(route('upgradeInfos.index'));
        }

        return view('upgrade_infos.show')->with('upgradeInfo', $upgradeInfo);
    }

    /**
     * Show the form for editing the specified upgrade_info.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $upgradeInfo = $this->upgradeInfoRepository->find($id);

        if (empty($upgradeInfo)) {
            Flash::error('Upgrade Info not found');

            return redirect(route('upgradeInfos.index'));
        }

        return view('upgrade_infos.edit')->with('upgradeInfo', $upgradeInfo);
    }

    /**
     * Update the specified upgrade_info in storage.
     *
     * @param  int              $id
     * @param Updateupgrade_infoRequest $request
     *
     * @return Response
     */
    public function update($id, Updateupgrade_infoRequest $request)
    {
        $upgradeInfo = $this->upgradeInfoRepository->find($id);

        if (empty($upgradeInfo)) {
            Flash::error('Upgrade Info not found');

            return redirect(route('upgradeInfos.index'));
        }

        $upgradeInfo = $this->upgradeInfoRepository->update($request->all(), $id);

        Flash::success('Upgrade Info updated successfully.');

        return redirect(route('upgradeInfos.index'));
    }

    /**
     * Remove the specified upgrade_info from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $upgradeInfo = $this->upgradeInfoRepository->find($id);

        if (empty($upgradeInfo)) {
            Flash::error('Upgrade Info not found');

            return redirect(route('upgradeInfos.index'));
        }

        $this->upgradeInfoRepository->delete($id);

        Flash::success('Upgrade Info deleted successfully.');

        return redirect(route('upgradeInfos.index'));
    }
}

resources/views/upgrade_infos/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('upgradeInfos.index') !!}">Upgrade Info</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Upgrade Info</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'upgradeInfos.store']) !!}

                                   @include('upgrade_infos.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/upgrade_infos/datatables_actions.blade.php
{!! Form::open(['route' => ['upgradeInfos.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('upgradeInfos.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('upgradeInfos.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/upgrade_infos/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('upgradeInfos.index') !!}">Upgrade Info</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Upgrade Info</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($upgradeInfo, ['route' => ['upgradeInfos.update', $upgradeInfo->id], 'method' => 'patch']) !!}

                              @include('upgrade_infos.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/upgrade_infos/fields.blade.php
<!-- Company Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('company_name', 'Company Name:') !!}
    {!! Form::text('company_name', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Address Field -->
<div class="form-group col-sm-6">
    {!! Form::label('address', 'Address:') !!}
    {!! Form::text('address', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Contact Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('contact_name', 'Contact Name:') !!}
    {!! Form::text('contact_name', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Ref Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ref_id', 'Ref Id:') !!}
    {!! Form::text('ref_id', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Place Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('place_id', 'Place Id:') !!}
    {!! Form::text('place_id', null, ['class' => 'form-control','maxlength' => 191,'maxlength' => 191,'maxlength' => 191]) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('upgradeInfos.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/upgrade_infos/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Upgrade Infos</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             upgrade_infos
                             <a class="pull-right" href="{{ route('upgradeInfos.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('upgrade_infos.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/upgrade_infos/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('upgradeInfos.index') }}">Upgrade Info</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('upgradeInfos.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('upgrade_infos.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/upgrade_infos/show_fields.blade.php
<!-- Company Name Field -->
<div class="form-group">
    {!! Form::label('company_name', 'Company Name:') !!}
    <p>{{ $upgradeInfo->company_name }}</p>
</div>

<!-- Address Field -->
<div class="form-group">
    {!! Form::label('address', 'Address:') !!}
    <p>{{ $upgradeInfo->address }}</p>
</div>

<!-- Contact Name Field -->
<div class="form-group">
    {!! Form::label('contact_name', 'Contact Name:') !!}
    <p>{{ $upgradeInfo->contact_name }}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{{ $upgradeInfo->email }}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{{ $upgradeInfo->phone }}</p>
</div>

<!-- Ref Id Field -->
<div class="form-group">
    {!! Form::label('ref_id', 'Ref Id:') !!}
    <p>{{ $upgradeInfo->ref_id }}</p>
</div>

<!-- Place Id Field -->
<div class="form-group">
    {!! Form::label('place_id', 'Place Id:') !!}
    <p>{{ $upgradeInfo->place_id }}</p>
</div>

resources/views/upgrade_infos/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}


<script>
    function Change_User_Stat(uid,name,stat_lv){

        var lv_name = "認証失敗";
        var stat_color = "danger";
        switch (stat_lv) {
            case 1:
                lv_name= "白金"
                stat_color = "success";
                break;

            case 2:
            lv_name= "鑽石"
            stat_color = "success";
            break;
        
            default:
                break;
        }
        var lv_html  =`<label class="btn btn-sm btn-${stat_color}  add-group-member">${ lv_name }</label>`

        swal.fire({
            title: `你確定要更改用戶 ${name} 的等級 ?`,
            html: `認証等級將會改為 ${lv_html}`,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'OK',
        }).then((result) => {
            var post_data = {
                status:stat_lv
            }

            $.ajax({
            url: "/api/upgrade_infos/"+uid,
            type: 'PUT',
            data: post_data,
            success: function (result) {
                LaravelDataTables.dataTableBuilder.ajax.reload();
                swal.fire({
            title: `更新成功`,
            icon: 'success',
            
            confirmButtonText: 'OK'});


            
            },
            error: function (result) {
               
            },
        });
        
        });
    }
    function status_render(data,type,full,meta){
        // let checked = row.email_verified_at === null ? '' : 'checked disabled';
        var stat_name = "未認証";
        var stat_color = "info";
        if(data == 1){
            stat_name = "白金";
            stat_color = "success";
        }
        if(data == 2){
            stat_name = "鑽石";
            stat_color = "primary";
        }
        if(data == -1){
            stat_name = "認証失敗"
            stat_color = "danger"
        }

        var label = `<label class="btn btn-sm btn-${stat_color} float-right add-group-member">${ stat_name }</label>`
        var upgrade_btn = `<button class="btn btn-sm btn-danger" onclick="Change_User_Stat(${full.id},'${full.contact_name}',-1)">退回</button>
        <button class="btn btn-sm btn-success" onclick="Change_User_Stat(${full.id},'${full.contact_name}',1)">認証為白金</button>
        <button class="btn btn-sm btn-primary" onclick="Change_User_Stat(${full.id},'${full.contact_name}',2)">認証為鑽石</button>
        
        `;
        return upgrade_btn+label ;
        // return data;
    }
</script>

    @endpush